### ISSUE TITLE
Unmatched video-question pairs.

### ISSUE THREAD

**Issue by kim1ng** [joez17/VideoNIAH#1]
Thanks for your great work!

<img width="1021" alt="image" src="https://github.com/joez17/VideoNIAH/assets/65498609/c16d4ae2-36ca-41eb-968b-8fac676a06e0">
I found that there are no apples in the video `video7014_ret_insert2.mp4`, but there is one in `video7014_ret_insert1.mp4`.

Can the questions and  all videos be matched?

**Comment by joez17** [comment]
Sorry for the mistake! We have updated the annotation file on huggingface website.
