### ISSUE TITLE
Asking about the evaluation code.

### ISSUE THREAD

**Issue by Leon1207** [joez17/VideoNIAH#2]
Hello, thanks for your great work.

I want to ask about why calculate this way:

for n, ac in acc.items():
        if ac==4:
            accuracy += 1
            
In this way, I got a very low ACC, about 0.07.
However, if I set ac == 1, I got a normal acc.

**Comment by DaozeZhang** [comment]
> Hello, thanks for your great work.
> 
> I want to ask about why calculate this way:
> 
> for n, ac in acc.items(): if ac==4: accuracy += 1
> 
> In this way, I got a very low ACC, about 0.07. However, if I set ac == 1, I got a normal acc.

The same issue. So could u please tell me the reason?

**Comment by Leon1207** [comment]
Because they use a 4-try evaluation, you can refer to their paper for more details!

**Comment by DaozeZhang** [comment]
Thanks a lot. So the model must correctly answer all the 4 questions to "get one score".
