### ISSUE TITLE
Do you consider adding Aria's performance?

### ISSUE THREAD

**Issue by teowu** [joez17/VideoNIAH#3]
Dear authors,

Thank you for your excellent work.
Our new LMM, Aria: https://huggingface.co/rhymes-ai/Aria also works well on long video scenarios. Would like to see its performance on this benchmark.

Best
Haoning

**Comment by joez17** [comment]
Dear Haoning,

We have tested Aria on VNBench and have updated the results on the leaderboard. You can find the updated performance details here: [VNBench Leaderboard](https://videoniah.github.io/).

We appreciate your interest in our work, and we're glad to see Aria's positive performance on long video scenarios.

Best regards,
VideoNIAH Team

**Comment by teowu** [comment]
Thank you so much for your evaluation!

Glad to see Aria performs so well on VNBench!

Best
Haoning
